// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package randomix.actions;

import java.io.FileInputStream;
import java.io.RandomAccessFile;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

/**
 * Generate a random image of a specific width/height.Each pixel is randomized. The result is a JPEG of the desired width/height.
 */
public class GenerateRandomFile extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject FileEntity;
	private java.lang.Long FileSize;

	public GenerateRandomFile(IContext context, IMendixObject FileEntity, java.lang.Long FileSize)
	{
		super(context);
		this.FileEntity = FileEntity;
		this.FileSize = FileSize;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		RandomAccessFile f = new RandomAccessFile("t", "rw");
		f.setLength(FileSize);
		FileInputStream stream = new FileInputStream(f.getFD());
		Core.storeFileDocumentContent(getContext(), FileEntity, stream);
		f.close();
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateRandomFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
